# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('resources', 'resources'),  # Включаем всю папку resources целиком
    ],
    hiddenimports=[
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.QtSvg',
        'requests',
        'sqlite3',
        # UI модули
        'ui',
        'ui.login_window',
        'ui.main_window',
        'ui.clients_tab',
        'ui.contracts_tab',
        'ui.crm_tab',
        'ui.crm_supervision_tab',
        'ui.dashboard_tab',
        'ui.dashboard_widget',
        'ui.dashboards',
        'ui.employees_tab',
        'ui.employee_reports_tab',
        'ui.reports_tab',
        'ui.salaries_tab',
        'ui.rates_dialog',
        'ui.custom_title_bar',
        'ui.custom_combobox',
        'ui.custom_dateedit',
        'ui.custom_message_box',
        'ui.file_gallery_widget',
        'ui.file_list_widget',
        'ui.file_preview_widget',
        'ui.variation_gallery_widget',
        'ui.flow_layout',
        'ui.update_dialogs',
        # Database
        'database',
        'database.db_manager',
        # Utils
        'utils',
        'utils.api_client',
        'utils.cache_manager',
        'utils.calendar_helpers',
        'utils.data_access',
        'utils.date_utils',
        'utils.db_security',
        'utils.db_sync',
        'utils.dialog_helpers',
        'utils.icon_loader',
        'utils.logger',
        'utils.message_helper',
        'utils.offline_manager',
        'utils.password_utils',
        'utils.pdf_generator',
        'utils.preview_generator',
        'utils.resource_path',
        'utils.sync_manager',
        'utils.tab_helpers',
        'utils.table_settings',
        'utils.tooltip_fix',
        'utils.unified_styles',
        'utils.update_manager',
        'utils.validators',
        'utils.yandex_disk',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='InteriorStudio',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Без консоли для Windows GUI приложения
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/icon256.ico',  # Иконка приложения (высокое разрешение 256x256)
)
