"""baseline: initial schema

Revision ID: 9b43f7eaae02
Revises: 
Create Date: 2026-02-20 12:57:57.447684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b43f7eaae02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('passport_series', sa.String(), nullable=True),
    sa.Column('passport_number', sa.String(), nullable=True),
    sa.Column('passport_issued_by', sa.String(), nullable=True),
    sa.Column('passport_issued_date', sa.String(), nullable=True),
    sa.Column('registration_address', sa.String(), nullable=True),
    sa.Column('organization_type', sa.String(), nullable=True),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('ogrn', sa.String(), nullable=True),
    sa.Column('account_details', sa.Text(), nullable=True),
    sa.Column('responsible_person', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('secondary_position', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('current_session_token', sa.String(), nullable=True),
    sa.Column('agent_color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_login'), 'employees', ['login'], unique=True)
    op.create_table('messenger_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_type', sa.String(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('stage_name', sa.String(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('use_auto_deadline', sa.Boolean(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messenger_scripts_id'), 'messenger_scripts', ['id'], unique=False)
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('stage_name', sa.String(), nullable=True),
    sa.Column('rate_per_m2', sa.Float(), nullable=True),
    sa.Column('area_from', sa.Float(), nullable=True),
    sa.Column('area_to', sa.Float(), nullable=True),
    sa.Column('fixed_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('executor_rate', sa.Float(), nullable=True),
    sa.Column('manager_rate', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('surveyor_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    op.create_table('action_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_history_id'), 'action_history', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('project_subtype', sa.String(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('contract_date', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('advance_payment', sa.Float(), nullable=True),
    sa.Column('additional_payment', sa.Float(), nullable=True),
    sa.Column('third_payment', sa.Float(), nullable=True),
    sa.Column('contract_period', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('contract_file_link', sa.String(), nullable=True),
    sa.Column('contract_file_yandex_path', sa.String(), nullable=True),
    sa.Column('contract_file_name', sa.String(), nullable=True),
    sa.Column('template_contract_file_link', sa.String(), nullable=True),
    sa.Column('template_contract_file_yandex_path', sa.String(), nullable=True),
    sa.Column('template_contract_file_name', sa.String(), nullable=True),
    sa.Column('tech_task_link', sa.String(), nullable=True),
    sa.Column('tech_task_yandex_path', sa.String(), nullable=True),
    sa.Column('tech_task_file_name', sa.String(), nullable=True),
    sa.Column('measurement_image_link', sa.String(), nullable=True),
    sa.Column('measurement_file_name', sa.String(), nullable=True),
    sa.Column('measurement_yandex_path', sa.String(), nullable=True),
    sa.Column('measurement_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_changed_date', sa.String(), nullable=True),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('yandex_folder_path', sa.String(), nullable=True),
    sa.Column('references_yandex_path', sa.String(), nullable=True),
    sa.Column('photo_documentation_yandex_path', sa.String(), nullable=True),
    sa.Column('act_planning_link', sa.String(), nullable=True),
    sa.Column('act_planning_yandex_path', sa.String(), nullable=True),
    sa.Column('act_planning_file_name', sa.String(), nullable=True),
    sa.Column('act_concept_link', sa.String(), nullable=True),
    sa.Column('act_concept_yandex_path', sa.String(), nullable=True),
    sa.Column('act_concept_file_name', sa.String(), nullable=True),
    sa.Column('info_letter_link', sa.String(), nullable=True),
    sa.Column('info_letter_yandex_path', sa.String(), nullable=True),
    sa.Column('info_letter_file_name', sa.String(), nullable=True),
    sa.Column('act_final_link', sa.String(), nullable=True),
    sa.Column('act_final_yandex_path', sa.String(), nullable=True),
    sa.Column('act_final_file_name', sa.String(), nullable=True),
    sa.Column('act_planning_signed_link', sa.String(), nullable=True),
    sa.Column('act_planning_signed_yandex_path', sa.String(), nullable=True),
    sa.Column('act_planning_signed_file_name', sa.String(), nullable=True),
    sa.Column('act_concept_signed_link', sa.String(), nullable=True),
    sa.Column('act_concept_signed_yandex_path', sa.String(), nullable=True),
    sa.Column('act_concept_signed_file_name', sa.String(), nullable=True),
    sa.Column('info_letter_signed_link', sa.String(), nullable=True),
    sa.Column('info_letter_signed_yandex_path', sa.String(), nullable=True),
    sa.Column('info_letter_signed_file_name', sa.String(), nullable=True),
    sa.Column('act_final_signed_link', sa.String(), nullable=True),
    sa.Column('act_final_signed_yandex_path', sa.String(), nullable=True),
    sa.Column('act_final_signed_file_name', sa.String(), nullable=True),
    sa.Column('advance_payment_paid_date', sa.String(), nullable=True),
    sa.Column('additional_payment_paid_date', sa.String(), nullable=True),
    sa.Column('third_payment_paid_date', sa.String(), nullable=True),
    sa.Column('advance_receipt_link', sa.String(), nullable=True),
    sa.Column('advance_receipt_yandex_path', sa.String(), nullable=True),
    sa.Column('advance_receipt_file_name', sa.String(), nullable=True),
    sa.Column('additional_receipt_link', sa.String(), nullable=True),
    sa.Column('additional_receipt_yandex_path', sa.String(), nullable=True),
    sa.Column('additional_receipt_file_name', sa.String(), nullable=True),
    sa.Column('third_receipt_link', sa.String(), nullable=True),
    sa.Column('third_receipt_yandex_path', sa.String(), nullable=True),
    sa.Column('third_receipt_file_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    op.create_index(op.f('ix_contracts_client_id'), 'contracts', ['client_id'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('file_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=False),
    sa.Column('server_path', sa.String(), nullable=True),
    sa.Column('yandex_path', sa.String(), nullable=True),
    sa.Column('public_url', sa.String(), nullable=True),
    sa.Column('preview_cache_path', sa.String(), nullable=True),
    sa.Column('is_synced_to_yandex', sa.Boolean(), nullable=True),
    sa.Column('last_sync_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_storage_id'), 'file_storage', ['id'], unique=False)
    op.create_index(op.f('ix_file_storage_uploaded_by'), 'file_storage', ['uploaded_by'], unique=False)
    op.create_table('messenger_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    op.create_index(op.f('ix_messenger_settings_id'), 'messenger_settings', ['id'], unique=False)
    op.create_table('norm_days_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('project_subtype', sa.String(), nullable=False),
    sa.Column('stage_code', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('stage_group', sa.String(), nullable=False),
    sa.Column('substage_group', sa.String(), nullable=True),
    sa.Column('base_norm_days', sa.Float(), nullable=False),
    sa.Column('k_multiplier', sa.Float(), nullable=True),
    sa.Column('executor_role', sa.String(), nullable=False),
    sa.Column('is_in_contract_scope', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_type', 'project_subtype', 'stage_code', name='uq_norm_template')
    )
    op.create_index(op.f('ix_norm_days_templates_id'), 'norm_days_templates', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_employee_id'), 'notifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('role_default_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission_name', name='uq_role_perm')
    )
    op.create_index(op.f('ix_role_default_permissions_id'), 'role_default_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_role_default_permissions_role'), 'role_default_permissions', ['role'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'permission_name', name='uq_employee_permission')
    )
    op.create_index(op.f('ix_user_permissions_employee_id'), 'user_permissions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_granted_by'), 'user_permissions', ['granted_by'], unique=False)
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('computer_name', sa.String(), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_user_sessions_employee_id'), 'user_sessions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_action_date'), 'activity_log', ['action_date'], unique=False)
    op.create_index(op.f('ix_activity_log_employee_id'), 'activity_log', ['employee_id'], unique=False)
    op.create_index(op.f('ix_activity_log_id'), 'activity_log', ['id'], unique=False)
    op.create_index(op.f('ix_activity_log_session_id'), 'activity_log', ['session_id'], unique=False)
    op.create_table('concurrent_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concurrent_edits_employee_id'), 'concurrent_edits', ['employee_id'], unique=False)
    op.create_index(op.f('ix_concurrent_edits_id'), 'concurrent_edits', ['id'], unique=False)
    op.create_index(op.f('ix_concurrent_edits_session_id'), 'concurrent_edits', ['session_id'], unique=False)
    op.create_table('crm_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approval_deadline', sa.String(), nullable=True),
    sa.Column('approval_stages', sa.Text(), nullable=True),
    sa.Column('project_data_link', sa.String(), nullable=True),
    sa.Column('tech_task_file', sa.String(), nullable=True),
    sa.Column('tech_task_date', sa.String(), nullable=True),
    sa.Column('survey_date', sa.String(), nullable=True),
    sa.Column('senior_manager_id', sa.Integer(), nullable=True),
    sa.Column('sdp_id', sa.Integer(), nullable=True),
    sa.Column('gap_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('surveyor_id', sa.Integer(), nullable=True),
    sa.Column('order_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['gap_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['sdp_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['senior_manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['surveyor_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_cards_contract_id'), 'crm_cards', ['contract_id'], unique=False)
    op.create_index(op.f('ix_crm_cards_gap_id'), 'crm_cards', ['gap_id'], unique=False)
    op.create_index(op.f('ix_crm_cards_id'), 'crm_cards', ['id'], unique=False)
    op.create_index(op.f('ix_crm_cards_manager_id'), 'crm_cards', ['manager_id'], unique=False)
    op.create_index(op.f('ix_crm_cards_sdp_id'), 'crm_cards', ['sdp_id'], unique=False)
    op.create_index(op.f('ix_crm_cards_senior_manager_id'), 'crm_cards', ['senior_manager_id'], unique=False)
    op.create_index(op.f('ix_crm_cards_surveyor_id'), 'crm_cards', ['surveyor_id'], unique=False)
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('public_link', sa.String(), nullable=True),
    sa.Column('yandex_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('preview_cache_path', sa.String(), nullable=True),
    sa.Column('file_order', sa.Integer(), nullable=True),
    sa.Column('variation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_files_id'), 'project_files', ['id'], unique=False)
    op.create_table('project_timeline_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('stage_code', sa.String(length=20), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('stage_group', sa.String(length=100), nullable=False),
    sa.Column('substage_group', sa.String(length=100), nullable=True),
    sa.Column('actual_date', sa.String(), nullable=True),
    sa.Column('actual_days', sa.Integer(), nullable=True),
    sa.Column('norm_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('executor_role', sa.String(length=50), nullable=False),
    sa.Column('is_in_contract_scope', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('raw_norm_days', sa.Float(), nullable=True),
    sa.Column('cumulative_days', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'stage_code', name='uq_timeline_contract_stage')
    )
    op.create_index(op.f('ix_project_timeline_entries_contract_id'), 'project_timeline_entries', ['contract_id'], unique=False)
    op.create_index(op.f('ix_project_timeline_entries_id'), 'project_timeline_entries', ['id'], unique=False)
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('advance_payment', sa.Float(), nullable=True),
    sa.Column('report_month', sa.String(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    op.create_table('supervision_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('senior_manager_id', sa.Integer(), nullable=True),
    sa.Column('dan_id', sa.Integer(), nullable=True),
    sa.Column('dan_completed', sa.Boolean(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('pause_reason', sa.Text(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['dan_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['senior_manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervision_cards_id'), 'supervision_cards', ['id'], unique=False)
    op.create_table('approval_stage_deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_card_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crm_card_id'], ['crm_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_stage_deadlines_id'), 'approval_stage_deadlines', ['id'], unique=False)
    op.create_table('messenger_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('crm_card_id', sa.Integer(), nullable=True),
    sa.Column('supervision_card_id', sa.Integer(), nullable=True),
    sa.Column('messenger_type', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_title', sa.String(), nullable=True),
    sa.Column('invite_link', sa.String(), nullable=True),
    sa.Column('avatar_type', sa.String(), nullable=True),
    sa.Column('creation_method', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['crm_card_id'], ['crm_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messenger_chats_id'), 'messenger_chats', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('crm_card_id', sa.Integer(), nullable=True),
    sa.Column('supervision_card_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=True),
    sa.Column('calculated_amount', sa.Float(), nullable=False),
    sa.Column('manual_amount', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('report_month', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('reassigned', sa.Boolean(), nullable=True),
    sa.Column('old_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['crm_card_id'], ['crm_cards.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['supervision_card_id'], ['supervision_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('stage_executors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_card_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['crm_card_id'], ['crm_cards.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_executors_id'), 'stage_executors', ['id'], unique=False)
    op.create_table('stage_workflow_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_card_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('current_substep_code', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=True),
    sa.Column('revision_file_path', sa.Text(), nullable=True),
    sa.Column('client_approval_started_at', sa.DateTime(), nullable=True),
    sa.Column('client_approval_deadline_paused', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crm_card_id'], ['crm_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_workflow_state_crm_card_id'), 'stage_workflow_state', ['crm_card_id'], unique=False)
    op.create_index(op.f('ix_stage_workflow_state_id'), 'stage_workflow_state', ['id'], unique=False)
    op.create_table('supervision_project_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervision_card_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['supervision_card_id'], ['supervision_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervision_project_history_id'), 'supervision_project_history', ['id'], unique=False)
    op.create_table('supervision_timeline_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervision_card_id', sa.Integer(), nullable=False),
    sa.Column('stage_code', sa.String(length=30), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.String(), nullable=True),
    sa.Column('actual_date', sa.String(), nullable=True),
    sa.Column('actual_days', sa.Integer(), nullable=True),
    sa.Column('budget_planned', sa.Float(), nullable=True),
    sa.Column('budget_actual', sa.Float(), nullable=True),
    sa.Column('budget_savings', sa.Float(), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('executor', sa.String(length=100), nullable=True),
    sa.Column('defects_found', sa.Integer(), nullable=True),
    sa.Column('defects_resolved', sa.Integer(), nullable=True),
    sa.Column('site_visits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supervision_card_id'], ['supervision_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supervision_card_id', 'stage_code', name='uq_sv_timeline_card_stage')
    )
    op.create_index(op.f('ix_supervision_timeline_entries_id'), 'supervision_timeline_entries', ['id'], unique=False)
    op.create_index(op.f('ix_supervision_timeline_entries_supervision_card_id'), 'supervision_timeline_entries', ['supervision_card_id'], unique=False)
    op.create_table('messenger_chat_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messenger_chat_id', sa.Integer(), nullable=False),
    sa.Column('member_type', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role_in_project', sa.String(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('invite_status', sa.String(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['messenger_chat_id'], ['messenger_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messenger_chat_members_id'), 'messenger_chat_members', ['id'], unique=False)
    op.create_table('messenger_message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messenger_chat_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('file_links', sa.Text(), nullable=True),
    sa.Column('sent_by', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['messenger_chat_id'], ['messenger_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messenger_message_log_id'), 'messenger_message_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messenger_message_log_id'), table_name='messenger_message_log')
    op.drop_table('messenger_message_log')
    op.drop_index(op.f('ix_messenger_chat_members_id'), table_name='messenger_chat_members')
    op.drop_table('messenger_chat_members')
    op.drop_index(op.f('ix_supervision_timeline_entries_supervision_card_id'), table_name='supervision_timeline_entries')
    op.drop_index(op.f('ix_supervision_timeline_entries_id'), table_name='supervision_timeline_entries')
    op.drop_table('supervision_timeline_entries')
    op.drop_index(op.f('ix_supervision_project_history_id'), table_name='supervision_project_history')
    op.drop_table('supervision_project_history')
    op.drop_index(op.f('ix_stage_workflow_state_id'), table_name='stage_workflow_state')
    op.drop_index(op.f('ix_stage_workflow_state_crm_card_id'), table_name='stage_workflow_state')
    op.drop_table('stage_workflow_state')
    op.drop_index(op.f('ix_stage_executors_id'), table_name='stage_executors')
    op.drop_table('stage_executors')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_messenger_chats_id'), table_name='messenger_chats')
    op.drop_table('messenger_chats')
    op.drop_index(op.f('ix_approval_stage_deadlines_id'), table_name='approval_stage_deadlines')
    op.drop_table('approval_stage_deadlines')
    op.drop_index(op.f('ix_supervision_cards_id'), table_name='supervision_cards')
    op.drop_table('supervision_cards')
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_table('salaries')
    op.drop_index(op.f('ix_project_timeline_entries_id'), table_name='project_timeline_entries')
    op.drop_index(op.f('ix_project_timeline_entries_contract_id'), table_name='project_timeline_entries')
    op.drop_table('project_timeline_entries')
    op.drop_index(op.f('ix_project_files_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_crm_cards_surveyor_id'), table_name='crm_cards')
    op.drop_index(op.f('ix_crm_cards_senior_manager_id'), table_name='crm_cards')
    op.drop_index(op.f('ix_crm_cards_sdp_id'), table_name='crm_cards')
    op.drop_index(op.f('ix_crm_cards_manager_id'), table_name='crm_cards')
    op.drop_index(op.f('ix_crm_cards_id'), table_name='crm_cards')
    op.drop_index(op.f('ix_crm_cards_gap_id'), table_name='crm_cards')
    op.drop_index(op.f('ix_crm_cards_contract_id'), table_name='crm_cards')
    op.drop_table('crm_cards')
    op.drop_index(op.f('ix_concurrent_edits_session_id'), table_name='concurrent_edits')
    op.drop_index(op.f('ix_concurrent_edits_id'), table_name='concurrent_edits')
    op.drop_index(op.f('ix_concurrent_edits_employee_id'), table_name='concurrent_edits')
    op.drop_table('concurrent_edits')
    op.drop_index(op.f('ix_activity_log_session_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_employee_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_action_date'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_employee_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_granted_by'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_employee_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_role_default_permissions_role'), table_name='role_default_permissions')
    op.drop_index(op.f('ix_role_default_permissions_id'), table_name='role_default_permissions')
    op.drop_table('role_default_permissions')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_employee_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_norm_days_templates_id'), table_name='norm_days_templates')
    op.drop_table('norm_days_templates')
    op.drop_index(op.f('ix_messenger_settings_id'), table_name='messenger_settings')
    op.drop_table('messenger_settings')
    op.drop_index(op.f('ix_file_storage_uploaded_by'), table_name='file_storage')
    op.drop_index(op.f('ix_file_storage_id'), table_name='file_storage')
    op.drop_table('file_storage')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_action_history_id'), table_name='action_history')
    op.drop_table('action_history')
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_messenger_scripts_id'), table_name='messenger_scripts')
    op.drop_table('messenger_scripts')
    op.drop_index(op.f('ix_employees_login'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
